apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-amqstreams-consumer-scaledobject
  namespace: kafka
  annotations:
    autoscaling.keda.sh/paused: "true"
spec:
  minReplicaCount: 1
  maxReplicaCount: 5
  scaleTargetRef:
    name: kafka-amqstreams-consumer
  triggers:
  - type: apache-kafka
    metadata:
      topic: my-topic
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:9092
      consumerGroup: my-group
      lagThreshold: "1"
      offsetResetPolicy: "latest"
