apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret-2
data:
  host: YW1xcDovL2RlZmF1bHRfdXNlcl9obUdaRmhkZXdxNjVQNGRJZHg3OnFjOThuNGlHRDdNWVhNQlZGY0lPMm10QjV2b0R1Vl9uQHJhYmJpdG1xLWNsdXN0ZXIucmFiYml0bXEtMi5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
